# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('idasset_log', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField()),
                ('showtime', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'asset_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('idassets', models.AutoField(primary_key=True, serialize=False)),
                ('assetname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('idattendance', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('idcolors', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentNames',
            fields=[
                ('iddepartment_names', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'department_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('iddepartments', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('iddesignations', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'designations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linkers',
            fields=[
                ('idlinkers', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'linkers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainDepartment',
            fields=[
                ('idmain_department', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'main_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('idproject_log', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('idprojects', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawStatusCodes',
            fields=[
                ('idraw_status_codes', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'raw_status_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawTemplateNames',
            fields=[
                ('idraw_template_names', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'raw_template_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('idsequences', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('idshots', models.AutoField(primary_key=True, serialize=False)),
                ('shotname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'shots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowCodes',
            fields=[
                ('idshow_codes', models.AutoField(primary_key=True, serialize=False)),
                ('show_codescol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'show_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusCodes',
            fields=[
                ('idstatus_codes', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'status_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('idtemplates', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('editable', models.IntegerField()),
            ],
            options={
                'db_table': 'templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('blood_group', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('authorised', models.IntegerField()),
                ('enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
