# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('idassets', models.AutoField(primary_key=True, serialize=False)),
                ('assetname', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Assetstatus',
            fields=[
                ('idassetstatus', models.AutoField(db_column='idprojectStatus', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'assetstatus',
            },
        ),
        migrations.CreateModel(
            name='Assosiate',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('blood_group', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('authorised', models.IntegerField()),
                ('enabled', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'assosiate',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idcolors', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('iddepartments', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='DepartmentName',
            fields=[
                ('iddepartment_names', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'department_name',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('iddesignations', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('idlinkers', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'linker',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('idprojects', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='RawStatusCode',
            fields=[
                ('idraw_status_codes', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'raw_status_code',
            },
        ),
        migrations.CreateModel(
            name='RawTemplateName',
            fields=[
                ('idraw_template_names', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'raw_template_name',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('idsequences', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('idshots', models.AutoField(primary_key=True, serialize=False)),
                ('shotname', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'shot',
            },
        ),
        migrations.CreateModel(
            name='ShowCode',
            fields=[
                ('idshow_codes', models.AutoField(primary_key=True, serialize=False)),
                ('show_codescol', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'show_codes',
            },
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('idstatus_codes', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'status_code',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('idtemplates', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('editable', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'template',
            },
        ),
    ]
