# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_asset_assetstatus_assosiate_color_department_departmentname_designation_linker_project_rawstatuscode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showcode',
            table='show_code',
        ),
    ]
